config/routes.rb
Rails.application.routes.draw do
  resources :ingredientes
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  get '/crear', to: 'pizzas#new'
  resources :pizzas, except: [:new]

  get '/signup', to: 'usuarios#new'
  resources :usuarios, except: [:new]

  resources :tipos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingrediente.rb
class Ingrediente < ApplicationRecord
    before_save { self.nombre = nombre.capitalize }

    has_attached_file :imagen, styles: { small: "200x200#", medium: "300x300>", thumb: "512x512#" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/

    validates :nombre, presence: true, length: { minimum: 2 }
    validates :precio, presence: true
    validates :tipo_id, presence: true

    belongs_to :tipo

    has_many :pizza_ingredientes
    has_many :pizzas, through: :pizza_ingredientes

end

app/models/pizza.rb
class Pizza < ApplicationRecord
    has_many :pizza_ingredientes
    has_many :ingredientes, through: :pizza_ingredientes
end

app/models/pizza_ingrediente.rb
class PizzaIngrediente < ApplicationRecord
    belongs_to :pizza
    belongs_to :ingrediente
end

app/models/tipo.rb
class Tipo < ApplicationRecord
    before_save { self.nombre = nombre.capitalize }

    validates :nombre, presence: true, length: { maximum: 20 }
    
    has_many :ingredientes
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    before_save { self.email = email.downcase }
 
    validates :chefname, presence: true, length: { maximum: 30 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/builders_controller.rb
class BuildersController < ApplicationController
    
    def crear
        @ingredientes = Ingrediente.where.not(nombre: ("Pan" || "Salsa de tomate"))
        @pan = Ingrediente.find_by(nombre: "Pan")
        @salsa = Ingrediente.find_by(nombre: "Salsa de tomate")
    end

end

app/controllers/ingredientes_controller.rb
class IngredientesController < ApplicationController
  before_action :set_ingrediente, only: [:show, :edit, :update, :destroy]

  # GET /ingredientes
  # GET /ingredientes.json
  def index
    @ingredientes = Ingrediente.all
  end

  # GET /ingredientes/1
  # GET /ingredientes/1.json
  def show
  end

  # GET /ingredientes/new
  def new
    @ingrediente = Ingrediente.new
    @tipos = Tipo.all
  end

  # GET /ingredientes/1/edit
  def edit
    @tipos = Tipo.all
  end

  # POST /ingredientes
  # POST /ingredientes.json
  def create
    @tipos = Tipo.all
    @ingrediente = Ingrediente.new(ingrediente_params)
    if @ingrediente.save
      flash[:success] = "Ingrediente agregado exitosamente "
      redirect_to ingrediente_path(@ingrediente)
    else
      render 'new'
    end
  end

  # PATCH/PUT /ingredientes/1
  # PATCH/PUT /ingredientes/1.json
  def update
    @tipos = Tipo.all
    if @ingrediente.update(ingrediente_params)
      flash[:success] = "Ingrediente editado exitosamente"
      redirect_to ingrediente_path(@ingrediente)
    else
      render 'ingredientes/edit'
    end
  end

  # DELETE /ingredientes/1
  # DELETE /ingredientes/1.json
  def destroy
    @ingrediente.destroy
    flash[:danger] = "Ingrediente eliminado exitosamente"
    redirect_to ingredientes_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingrediente
      @ingrediente = Ingrediente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingrediente_params
      params.require(:ingrediente).permit(:nombre, :precio, :tipo_id, :imagen)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController

    def new
        @pizza = Pizza.new
        #Trae los elementos base para la pizza. "Pan y salsa"
        @base = Tipo.where(nombre: "Base")
        #Trae todos los tipos ingredientes y sus ing. asociados excepto "Base"
        @tipos = Tipo.where.not(nombre: "Base")
    end

end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
    def index
        @tipos = Tipo.all
    end
    
    def new
        @tipo = Tipo.new
    end

    def create
        @tipo = Tipo.new(tipo_params)
        if @tipo.save
            flash[:success] = "Tipo de ingrediente agregado exitosamente"
            redirect_to tipo_path(@tipo)
        else
            render 'new'
        end
    end

    def show
        @tipo = Tipo.find(params[:id])
        # Paginate the recipes in chefs show page
    end

    def edit
        @tipo = Tipo.find(params[:id])
    end

    def update
        @tipo = Tipo.find(params[:id])
        if @tipo.update(tipo_params)
            flash[:success] = "Tipo de ingrediente actualizado exitosamente"
            redirect_to @tipo
        else
            render 'edit'
        end
    end

    def destroy
        @tipo = Tipo.find(params[:id])
        @tipo.destroy
        flash[:danger] = "Tipo de ingrediente eliminado"
        redirect_to tipos_path
        
    end

    private

        def tipo_params
            params.require(:tipo).permit(:nombre)
        end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
    def index
        @usuarios = Usuario.all
    end
    
    def new
        @usuario = Usuario.new
    end

    def create
        @usuario = Usuario.new(usuario_params)
        if @usuario.save
            flash[:success] = "Bienvenido #{@usuario.nombre} #{@usuario.apellido} a Pizza Builder!"
            redirect_to usuario_path(@usuario)
        else
            render 'new'
        end
    end

    def show
        @usuario = Usuario.find(params[:id])
        # Paginate the recipes in chefs show page
    end

    def edit
        @usuario = Usuario.find(params[:id])
    end

    def update
        @usuario = Usuario.find(params[:id])
        if @usuario.update(usuario_params)
            flash[:success] = "Su cuenta ha sido actualizada exitosamente"
            redirect_to @usuario
        else
            render 'edit'
        end
    end

    def destroy
        @usuario = Usuario.find(params[:id])
        @usuario.destroy
        flash[:danger] = "Chef and all associated recipes have been deleted!"
        redirect_to usuarios_path
        
    end

    private

        def usuario_params
            params.require(:usuario).permit(:nombre, :apellido, :email)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def show_alert_type(alert)
        alerts = { "success" => "check", "danger" => "error_outline" }
        alerts[alert]
    end
end

app/helpers/builders_helper.rb
module BuildersHelper
end

app/helpers/ingredientes_helper.rb
module IngredientesHelper
end

app/views/ingredientes/_form.html.erb
<div class="row">
    <div class="col-md-12">
        <%= form_for(@ingrediente, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group col-md-8 offset-2">
                <%= f.label :nombre %>
                <%= f.text_field :nombre, class: "form-control", maxlength: 60, placeholder: "Nombre del ingrediente", autofocus: true %>
            </div>

            <div class="form-group col-md-8 offset-2">
                <%= f.label :precio %>
                <%= f.number_field :precio, class: "form-control", placeholder: "Ingrese el precio", step: :any %>
            </div>

            <div class="form-group col-md-8 offset-2">
                <%= f.label :tipo_id %>
                <%= f.select :tipo_id, @tipos.collect{ |t| [t.nombre, t.id] }, {:include_blank => 'Seleccione'}, class: "custom-select" %>
            </div>
            
            <br>

            <div class="col-md-8 offset-2">
                <div class="custom-file">
                    <%= f.label "Seleccionar imagen", class: "custom-file-label" %>
                    <%= f.file_field :imagen, class: "custom-file-input" %>
                </div>
            </div>

            <br>

            <div class="form-group col-md-8 offset-2">
                <%= f.submit(@ingrediente.new_record? ? "Crear ingrediente" : "Editar ingrediente",
                                                            class: "btn btn-primary") %>
            </div>
        <% end %>
        <div class="col-md-4 offset-4 color-match">
            [ <%= link_to "Cancelar y regresar a la lista de ingredientes", ingredientes_path %> ]
        </div>
    </div>
</div>

app/views/ingredientes/edit.html.erb
<br>
<h1 align="center">Editar Ingrediente</h1>
<hr>

<%= render 'form', ingrediente: @ingrediente %>

app/views/ingredientes/index.html.erb
<br>
<h1 align="center">Ingredientes</h1>
<hr>

<br>
<div class="row">
    <div class="col-md-8 offset-2">
        <h4 align="center"> <%= link_to "Crear nuevo", new_ingrediente_path %> </h4>
    </div>
</div>
<br>

<% @ingredientes.each do |ingrediente| %>

    <div class="row section-tabs">
    <div class="col-md-6 mx-auto offset-2">
        <div class="card card-body justify-content-center bg-light">
            <div class="tim-typo">
                <h4 class="title" align="center"> <%= link_to ingrediente.nombre, ingrediente_path(ingrediente) %> </h4>
            </div>
            <p class="card-text" align="center"> <%= ingrediente.precio %> córdobas</p>
            <p align="center"> <%= image_tag ingrediente.imagen.url(:small) %> </p>
            <p align="center"> 
            <span class="quiet" ><small class="card-text">Created <%=time_ago_in_words(ingrediente.created_at)%> ago</small></span>
            </p>
        </div>
    </div>
    </div>

    
<% end %>

<br>

app/views/ingredientes/new.html.erb
<br>
<h1 align="center">Nuevo Ingrediente</h1>

<hr>

<%= render 'form', ingrediente: @ingrediente %>

app/views/ingredientes/show.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-2 mx-auto">
        <div class="card mx-auto">
            <div class="card-body bg-light">
                <h4 class="center card-title"> <%= @ingrediente.nombre %> </h4>

                <div class="row">
                    <div class="col-6">
                        <h4 class="center description"><strong>Precio: </strong></h4>
                        <p class="center">C$ <%= @ingrediente.precio %></p>
                    </div>

                    <div class="col-6">
                        <h4 class="center description"><strong>Tipo: </strong></h4>
                        <p class="center"> <%= @ingrediente.tipo.nombre %> </p>
                    </div>    
                </div>


                <p class="center"> <%= image_tag @ingrediente.imagen.url(:medium) %> </p>

                <hr>
                <div class="ingrediente-actions center">
                    <%= link_to "Editar ingrediente", edit_ingrediente_path(@ingrediente), class: "btn btn-sm btn-warning" %>
                    <%= link_to "Eliminar ingrediente", ingrediente_path(@ingrediente), method: :delete, 
                                                data: { confirm: "¿Seguro quieras borrar este ingrediente?" },
                                                class: "btn btn-sm btn-danger" %>
                    <%= link_to "Regresar a la lista", ingredientes_path, class: "btn btn-sm btn-primary" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible">
        <div class="container">
            <div class="alert-icon">
                <i class="material-icons"> <%= show_alert_type(name) %> </i>
            </div>
        </div>
        <b> <%= msg %> </b> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>            
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-primary fixed-top" id="sectionsNav">
  <div class="container">
    <div class="navbar-translate">
      <%= link_to "PizzaBuilder", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to crear_path, class: "nav-link" do %>
           <i class="material-icons">local_pizza</i> Crear pizza
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to ingredientes_path, class: "nav-link" do %>
            <i class="material-icons">shopping_basket</i> Ingredientes
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to tipos_path, class: "nav-link" do %>
            <i class="material-icons">list</i> Tipo ingrediente
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!--        end primary navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>PizzaBuilder</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700' %>
    <%= stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="index-page">
    <%= render 'layouts/navigation' %>

    <%= render 'layouts/messages' %>

    <div class="main main-raised">
      <div class="section">
        <div class="container">
          <br><br>    
          <%= yield %>
        </div>
      </div>
    </div>
    
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="page-header header-filter clear-filter purple-filter-soft home-background" data-parallax="true">
  <div class="container">
    <div class="row">
      <div class="col-md-8 ml-auto mr-auto">
        <div class="brand">
          <h1>Armá tu pizza, creala al gusto.</h1>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="main main-raised">
  <div class="container">
    <br>
    <h3 class="title" align="center">Creadores</h3>
    <br>
    <div class="row">
      <div class="col-4 offset-2">
        <div class="col-sm-4 offset-1">
          <img src="/assets/ee.jpg" alt="Circle Image" class="img-raised rounded-circle img-fluid">
        </div>
        <div class="name">
          <h3 class="title">Manuel Torrez</h3>
          <h6>Desarrollador</h6>
          <a href="http://github.com/manueltorrez" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-github"></i></a>
          <a href="http://twitter.com/arubyist" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
          <a href="http://facebook.com/manueltorrezvado" class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-facebook"></i></a>
          <br>
        </div>
      </div>

      <div class="col-4 offset-2">
        <div class="col-sm-4 offset-1">
          <img src="/assets/ee.jpg" alt="Circle Image" class="img-raised rounded-circle img-fluid">
        </div>
        <div class="name">
          <h3 class="title">Adriana Rosales</h3>
          <h6>Desarrolladora</h6>
          <a href="http://github.com/adrianasalome31" class="btn btn-just-icon btn-link btn-dribbble"><i class="fa fa-github"></i></a>
          <a href="http://twitter.com/adrianasalome31" class="btn btn-just-icon btn-link btn-twitter"><i class="fa fa-twitter"></i></a>
          <a href="http://facebook.com/adriana.salome.5" class="btn btn-just-icon btn-link btn-pinterest"><i class="fa fa-facebook"></i></a>
          <br>
        </div>
      </div>
    </div>
  </div>
  <br>
</div>

app/views/pizzas/new.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1 align="center" class="title">Crear pizza</h1>
<hr>

<div class="row">

    <div class="col">
        <%= form_for(@pizza, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        
           <% @tipos.each do |tipo| %>
                <h4 class="title"> <%= tipo.nombre %> </h4>
                <hr>
                    
                <% tipo.ingredientes.each do |ingrediente| %>
                    <div class="form-check">
                        <%= check_box_tag :ingrediente_ids, ingrediente.id, @pizza.ingredientes.include?(ingrediente), :name => 'pizza[ingrediente_ids][]', class: "ingrediente-check" -%>
                        <%= label_tag :ingrediente_ids, ingrediente.nombre -%>
                        
                    </div>
                <% end %>
           <% end %>

           <%= f.submit "Ordenar", class: "btn btn-rose" %> 
           
        <% end %>
    </div>

    <div class="col base-pizza">
        <% @base.each do |b| %>
            <% b.ingredientes.each do |ingrediente| %>
                <%= image_tag ingrediente.imagen.url %>
            <% end %>
        <% end %>

        <% @tipos.each do |t| %>
            <% t.ingredientes.each do |ingrediente| %>
                <%= image_tag ingrediente.imagen.url, class: "ingrediente ingrediente-oculto", 
                id: "ingrediente-img"+ingrediente.id.to_s, type: "hidden" %>
            <% end %>
            
        <% end %>
    </div>

    <div class="col">
        <h4 align="center" class="title">Precio</h4>
        <div class="ingrediente-precio"></div>
    </div>
</div>

app/views/tipos/_form.html.erb
<div class="row">
    <div class="col-md-12">
        <%= form_for(@tipo, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group col-md-8 offset-2">
                <%= f.label :nombre %>
                <%= f.text_field :nombre, class: "form-control", maxlength: 20, placeholder: "Nombre del tipo de ingrediente", autofocus: true %>
            </div>

            <div class="form-group col-md-8 offset-2">
                <%= f.submit(@tipo.new_record? ? "Crear tipo de ingrediente" : "Editar tipo de ingrediente",
                                                            class: "btn btn-primary") %>
            </div>
        <% end %>
        <div class="col-md-4 offset-4 color-match">
            [ <%= link_to "Regresar a la lista de tipos de ingredientes", tipos_path %> ]
        </div>
    </div>
</div>

app/views/tipos/edit.html.erb
<br>
<h1 align="center">Editar tipo de ingrediente</h1>
<hr>

<%= render 'form', tipo: @tipo %>

app/views/tipos/index.html.erb
<br>
<h1 align="center">Tipos de ingredientes</h1>
<hr>

<br>
<div class="row">
    <div class="col-md-8 offset-2">
        <h4 align="center"> <%= link_to "Crear nuevo", new_tipo_path %> </h4>
    </div>
</div>
<br>

<% @tipos.each do |tipo| %>

    <div class="row">
    <div class="col-md-6 mx-auto offset-2">
        <div class="card card-body justify-content-center bg-light">
            <div class="tim-typo">
                <h4 class="title" align="center"> <%= link_to tipo.nombre, tipo_path(tipo) %> </h4>
            </div>
            <p align="center"> 
            <span class="quiet" ><small class="card-text">Created <%=time_ago_in_words(tipo.created_at)%> ago</small></span>
            </p>
        </div>
        <br>  
    </div>
    </div>

    
<% end %>

<br>

app/views/tipos/new.html.erb
<br>
<h1 align="center">Nuevo tipo de ingrediente</h1>

<hr>

<%= render 'form', tipo: @tipo %>

app/views/tipos/show.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2 mx-auto">
        <div class="card mx-auto">
            <div class="card-body bg-light">
                <h4 class="center card-title"> Tipo: <%= @tipo.nombre %> </h4>
                <br>

                <hr>
                <div class="ingrediente-actions center">
                    <%= link_to "Editar tipo de ingrediente", edit_tipo_path(@tipo), class: "btn btn-sm btn-warning" %>
                    <%= link_to "Eliminar tipo de ingrediente", tipo_path(@tipo), method: :delete, 
                                                data: { confirm: "¿Seguro quieras borrar este tipo de ingrediente?" },
                                                class: "btn btn-sm btn-danger" %>
                    <%= link_to "Regresar a la lista", tipos_path, class: "btn btn-sm btn-primary" %>
                </div>
            </div>
        </div>
    </div>
</div>